import mongoose, { Schema } from 'mongoose';
import { ITrip } from '../types';

// ─── Day Plan Sub-Schema ──────────────────────────────────────────────────────
// Each day has morning / afternoon / evening activity lists + travel tips
const dayPlanSchema = new Schema(
  {
    day: { type: Number, required: true },
    title: { type: String, required: true },
    morning: { type: [String], default: [] },
    afternoon: { type: [String], default: [] },
    evening: { type: [String], default: [] },
    tips: { type: String, default: '' },
  },
  { _id: false }
);

// ─── Hotel Sub-Schema ─────────────────────────────────────────────────────────
const hotelSchema = new Schema(
  {
    name: { type: String, required: true },
    rating: { type: Number, required: true, min: 1, max: 5 },
    description: { type: String, required: true },
    // Optional enrichment fields
    pricePerNight: { type: Number },
    address: { type: String },
    amenities: { type: [String] },
  },
  { _id: false }
);

// ─── Budget Sub-Schema ────────────────────────────────────────────────────────
const budgetSchema = new Schema(
  {
    accommodation: { type: Number, required: true },
    food: { type: Number, required: true },
    transportation: { type: Number, required: true },
    activities: { type: Number, required: true },
    total: { type: Number, required: true },
    currency: { type: String, required: true, default: 'USD' },
  },
  { _id: false }
);

// ─── Trip Schema ──────────────────────────────────────────────────────────────
const tripSchema = new Schema<ITrip>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    destination: {
      type: String,
      required: [true, 'Destination is required'],
      trim: true,
    },
    numberOfDays: {
      type: Number,
      required: [true, 'Number of days is required'],
      min: [1, 'Minimum 1 day'],
      max: [30, 'Maximum 30 days'],
    },
    budgetType: {
      type: String,
      enum: ['budget', 'moderate', 'luxury'],
      required: [true, 'Budget type is required'],
    },
    interests: {
      type: [String],
      required: true,
      validate: {
        validator: (v: string[]) => v.length > 0,
        message: 'At least one interest is required',
      },
    },
    itinerary: { type: [dayPlanSchema], default: [] },
    hotels: { type: [hotelSchema], default: [] },
    budget: { type: budgetSchema, required: true },
    packingChecklist: { type: [String], default: [] },
    /** Tells you whether this trip was generated by Gemini AI or the fallback engine */
    generatedBy: {
      type: String,
      enum: ['gemini', 'fallback'],
      required: true,
      default: 'fallback',
    },
    generationModel: {
      type: String,
      required: true,
      default: 'rule-based-engine',
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Compound index for efficient per-user queries sorted by date
tripSchema.index({ userId: 1, createdAt: -1 });

const Trip = mongoose.model<ITrip>('Trip', tripSchema);
export default Trip;
